name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.SERVICE_PERSONAL_ACCESS_TOKEN}}
          submodules: true
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint
        run: ./gradlew app:ktlint
      - name: CheckStyle
        run: ./gradlew app:checkstyle
